### ISSUE TITLE
Add a Detailed Vehicle Builds section

### ISSUE THREAD

**Issue by gmorph** [diydrones/ardupilot-wiki-issue-tracker#115]
Use the vehicles in the getting started section to seed this page. This item spawned off #111

**Comment by hamishwillee** [comment]
I made the following changes:

1. Added [Detailed Vehicle Builds](http://rover.ardupilot.com/wiki/common-common-airframe-builds/) to the menu. Updated this page to refer to "common frames" rather than "common airframes".
2. Split out [PX4 Rover Build with Brushless Traxxas Stampede 4WD Truck](http://rover.ardupilot.com/wiki/px4-rover-build-with-brushless-traxxas-stampede-4wd-truck/) from the quickstart and subedited. Added to the menu.
3. Minor subedit [Rover PX4 Wiring and Quick Start](http://rover.ardupilot.com/wiki/rover-px4-quickstart/) after splitting out above page (and linking to it)

@gmorph Can you please do quick sanity check. Also are there any other vehicle builds we can split out?

Otherwise I think this can be closed?

**Comment by gmorph** [comment]
Reviewed and it looks great.  It will be very good if we can add more
vehicles to that page.  I think the equivalent for Plane and Copter would
be great.

Thanks, Grant.

On 5 August 2015 at 10:36, Hamish Willee <notifications@github.com> wrote:

> I made the following changes:
>
>    1. Added Detailed Vehicle Builds
>    <http://rover.ardupilot.com/wiki/common-common-airframe-builds/> to
>    the menu. Updated this page to refer to "common frames" rather than "common
>    airframes".
>    2. Split out PX4 Rover Build with Brushless Traxxas Stampede 4WD Truck
>    <http://rover.ardupilot.com/wiki/px4-rover-build-with-brushless-traxxas-stampede-4wd-truck/>
>    from the quickstart and subedited. Added to the menu.
>    3. Minor subedit Rover PX4 Wiring and Quick Start
>    <http://rover.ardupilot.com/wiki/rover-px4-quickstart/> after
>    splitting out above page (and linking to it)
>
> @gmorph <https://github.com/gmorph> Can you please do quick sanity check.
> Also are there any other vehicle builds we can split out?
>
> Otherwise I think this can be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/115#issuecomment-127803889>
> .
>



-- 
Thanks

Grant

**Comment by hamishwillee** [comment]
> I think the equivalent for Plane and Copter would be great.

Way ahead of you - equivalent sections linked below. Plane only has the Bixler, while Copter has a few builds and some generic build information that doesn't quite fit anywhere else. As you say, extending both Rover and Plane with more real example builds would be great.

* [Plane](http://plane.ardupilot.com/wiki/common-common-airframe-builds/)
* [Copter](http://copter.ardupilot.com/wiki/common-common-airframe-builds/)

Closing this as complete.
