### ISSUE TITLE
Adding a New Flight Mode (Copter Code Overview)

### ISSUE THREAD

**Issue by MaxcxX** [diydrones/ardupilot-wiki-issue-tracker#211]
[Adding a New Flight Mode (Copter Code Overview)](http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/)

Hi,

I have created my new flight mode by following this tutorial : 
http://dev.ardupilot.com/wiki/apmcopter-adding-a-new-flight-mode/

the compilation is successful, but the new flight mode don't display on Mission Planner menu.

What is the procedure to display the new flight mode on Mission Planner menu ?

Thank you in advance.

**Comment by rmackay9** [comment]
So the issue here is that parameter description for the FLTMODEX parameters (where "X" is replaced by a number between 1 and 6) must be updated in the ardupilot/master branch because that's where the MP gets it from.  Until then though you can still set the FLTMODEX parameter directly and you should find it's possible to switch into the new mode with the transmitter.

I'm going to close this issue if that's ok although I'll still see replies post here.
