### ISSUE TITLE
Fail with the instructions to take off in the MAVProxy command prompt

### ISSUE THREAD

**Issue by dgdstroyer** [diydrones/ardupilot-wiki-issue-tracker#240]
Hi
I have a problem with the instructions to take off the copter. When I write into the MAVProxy command prompt:
param load ..\Tools\autotest\copter_params.parm

Appearing the next message: 
failed to open file '..Toolsautotestcopter_params.parm'

Later I write into the MAVProxy command prompt:

mode guided
arm throttle
takeoff 40

and the console show me:

Mode GUIDED
APM: PreArm: Need 3D Fix
Got MAVLink msg: COMMAND_ACK {command : 400, result : 4}
Got MAVLink msg: COMMAND_ACK {command : 22, result : 4}

The Alt it is not change. someone can help me please?
Sorry, my English is very awful but I hope that you understand me xD. Thanks

**Comment by hamishwillee** [comment]
Hi @dgdstroyer,

This forum is for issues about the documentation, while this sounds like a technical support query (for a start, there is no link to a problem document). The best place for technical support questions is the APM forums.

That said, your second problem is because the param load failed - basically the default parameters on SITL are "unforgiving" - the vehicle isn't in a good state to fly so it fails a whole bunch of checks. Normally you load this set identified, and also for SITL (only) you might turn off ALL arming checks.

So the question is, why is the load command failing. You basically need to confirm that the copter_params.parm is in the specified location with respect to the folder in which you started mavproxy.

Closing this query as invalid.
