### ISSUE TITLE
Add link to Python source code

### ISSUE THREAD

**Issue by zlite** [diydrones/ardupilot-wiki-issue-tracker#89]
On this page (http://python.dronekit.io/examples/running_examples.html) we say "It is probably best to take a look at the python code before running it", but don't give a link to that source code. The code is here:

https://github.com/zlite/dronekit-python/blob/master/example/small_demo/small_demo.py

**Comment by hamishwillee** [comment]
Hi Chris

The whole line isn't very useful because there is no need in this particular document to look at the source code (at this point we are not examining code, just verifying our environment).

In any case, as soon as my [next pull request](https://github.com/diydrones/dronekit-python/pull/94) goes in the line will disappear as part of a significant restructure. 

I am therefore closing this, and I will send you a more detailed explanation of the upcoming changes offline.

Regards
Hamish

PS, Best to post these in [dronekit-python](https://github.com/diydrones/dronekit-python/issues).
